# Generated by Django 5.0 on 2024-01-12 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 12, 6, 55, 1, 872430, tzinfo=datetime.timezone.utc)),
        ),
    ]
