# Generated by Django 5.0 on 2024-01-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter_table',
            name='last_payment_entry_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counter_table',
            name='last_task_id',
            field=models.IntegerField(default=0),
        ),
    ]
