# Generated by Django 5.0 on 2023-12-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor_register',
            name='credential_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
