# Generated by Django 5.0 on 2024-01-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0003_labor_register_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor_register',
            name='otp',
            field=models.CharField(default='569864', max_length=50),
        ),
    ]
